### ISSUE TITLE
Create Lo-fi for Landing page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#20]
Create low fidelity design of the landing page

**Comment by Ecosanachi** [comment]
[Proj-t-c-gen-Team78.zip](https://github.com/zuri-training/tc-gen-team78/files/9254370/Proj-t-c-gen-Team78.zip)
[Proj-t-c-gen-Team78 (2).zip](https://github.com/zuri-training/tc-gen-team78/files/9254402/Proj-t-c-gen-Team78.2.zip)

**Comment by Ecosanachi** [comment]
![low fi 1 (2)](https://user-images.githubusercontent.com/105288646/182699079-651b9ec7-d9dd-4340-af56-46969a804b2e.png)
![low fi 2 (2)](https://user-images.githubusercontent.com/105288646/182699087-98b5c5f2-eda3-45d8-9c62-e0ea26b2e509.png)

**Comment by Holardiplenty123** [comment]
![lowfi](https://user-images.githubusercontent.com/110137932/183243448-bfc53227-7da4-4e75-b774-18595748a60c.jpg)

**Comment by Holardiplenty123** [comment]
Done

**Comment by Horluwatimi** [comment]
>
<img width="1439" alt="Desktop (2)" src="https://user-images.githubusercontent.com/105248194/183247962-4244b2d2-0def-4500-9d1d-4cbd4cd19e7f.png">
![Tablet view](https://user-images.githubusercontent.com/105248194/183247966-90501016-6efd-4d94-8ea4-e16db64148de.png)
![Page_Mobile view (1)](https://user-images.githubusercontent.com/105248194/183247969-ca22d30d-82ca-4f3f-8150-1f62dc2563bc.png)

**Comment by Horluwatimi** [comment]
mages.githubusercontent.com/105248194/183247969-ca22d30d-82ca-4f3f-8150-1f62dc2563bc.png

**Comment by Horluwatimi** [comment]
![Uploading lowfi.png…]()
