### ISSUE TITLE
Create Lo-fi for Information entry page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#22]
Create Low-Fidelity Design of Information entry page, Dashboard inclusive.

**Comment by Alatharee21** [comment]
@misterdan-a please upload the Lo-fi of this page sir

**Comment by misterdan-a** [comment]
![T C Generator_Stage 2](https://user-images.githubusercontent.com/105433488/183509579-981394cd-0ba0-4350-88d4-aaf8b192af7e.png)
![Interaction page-Dan](https://user-images.githubusercontent.com/105433488/183509664-e4b7d19f-3e3a-47be-8e34-fede75870440.png)
![Privacy Policy Generator_Stage 1](https://user-images.githubusercontent.com/105433488/183509677-96ffda23-241f-4ee5-9fb0-db7159572051.png)
![Privacy Policy Generator_Stage 2](https://user-images.githubusercontent.com/105433488/183509689-b919a55c-4093-4e81-b64e-4622237ba607.png)
![T C Generator_Stage 1](https://user-images.githubusercontent.com/105433488/183509755-8074cd6c-8aae-4644-b95a-680c1fc5f475.png)

**Comment by misterdan-a** [comment]
![T C Generator_Stage 2](https://user-images.githubusercontent.com/105433488/183509579-981394cd-0ba0-4350-88d4-aaf8b192af7e.png)
![Interaction page-Dan](https://user-images.githubusercontent.com/105433488/183509664-e4b7d19f-3e3a-47be-8e34-fede75870440.png)
![Privacy Policy Generator_Stage 1](https://user-images.githubusercontent.com/105433488/183509677-96ffda23-241f-4ee5-9fb0-db7159572051.png)
![Privacy Policy Generator_Stage 2](https://user-images.githubusercontent.com/105433488/183509689-b919a55c-4093-4e81-b64e-4622237ba607.png)
![T C Generator_Stage 1](https://user-images.githubusercontent.com/105433488/183509755-8074cd6c-8aae-4644-b95a-680c1fc5f475.png)

**Comment by Alatharee21** [comment]
Gracias
