### ISSUE TITLE
Create Lo-fi for generated text page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#23]
Create low fidelity design for text generated page as a response to inform entered.

**Comment by Efetur** [comment]
Done with it
![Uploading IMG-20220806-WA0009.jpg…]()

**Comment by Efetur** [comment]
![IMG-20220806-WA0009](https://user-images.githubusercontent.com/105781279/183243879-91e81960-2ca0-454e-98a2-4b0b19a3c701.jpg)

**Comment by Samysweet** [comment]
<img width="1440" alt="Generated text (Privacy Policy)" src="https://user-images.githubusercontent.com/105239555/183245136-982c1014-b1e4-4d46-b19e-6ee0e4e4617f.png">
<img width="1440" alt="Generated text (T C)" src="https://user-images.githubusercontent.com/105239555/183245138-0eaabfac-2995-41bc-961a-88f9abc14a0e.png">
Done
