### ISSUE TITLE
Complete style guide

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#26]
Complete style guide; Color style, Button state, field state, Iconography.

**Comment by misterdan-a** [comment]
![Typography Style guide](https://user-images.githubusercontent.com/105433488/182425361-78deaf8d-df3d-45c1-9795-45a4563d8500.png)
![Buttons   Links](https://user-images.githubusercontent.com/105433488/182425364-af5b3e96-b302-4187-a00b-55f7e43b7177.png)
![Checkboxes](https://user-images.githubusercontent.com/105433488/182425369-da59d6d8-d34c-45a9-b10b-5070048ef4fc.png)
![Color Style](https://user-images.githubusercontent.com/105433488/182425372-5a57cd7e-16f8-4a4e-8620-9587ec9d5fb0.png)
[Link to Figma File.txt](https://github.com/zuri-training/tc-gen-team78/files/9244043/Link.to.Figma.File.txt)
![Radio Button](https://user-images.githubusercontent.com/105433488/182425380-74763789-0291-4b27-8926-f3b422ed7e6d.png)
![Spacers](https://user-images.githubusercontent.com/105433488/182425382-7ea72ad0-f713-4586-bc62-d9f72cd260ce.png)
![Typography Style guide - Mobile](https://user-images.githubusercontent.com/105433488/182425386-ecac0248-ccaa-4e95-9263-a301a56f4e76.png)

**Comment by misterdan-a** [comment]
The files can be found on Figma by following the link below
https://www.figma.com/file/FyXNAMzxSQY49B9HW7ElMQ/Proj-t-c-gen-Team78?node-id=0%3A1
