### ISSUE TITLE
Create Hi-fi of Landing page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#29]
Create High-Fidelity of landing page Design.

**Comment by Ecosanachi** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/105288646/182713157-3c308f40-5f5f-4437-821e-99cfd7eb7071.png)
![Screenshot (33)](https://user-images.githubusercontent.com/105288646/182713163-f731d826-8ded-40c0-b775-1d4c89cd8229.png)
![Screenshot (34)](https://user-images.githubusercontent.com/105288646/182713167-08ee81d1-1206-4a90-8e88-23a54cc204f6.png)
![Screenshot (35)](https://user-images.githubusercontent.com/105288646/182713169-4c685b01-9f5a-4cfe-9200-48595f5bade7.png)
![Screenshot (36)](https://user-images.githubusercontent.com/105288646/182713174-8c20ca9f-1523-4e94-90a5-4257be308369.png)
![Screenshot (37)](https://user-images.githubusercontent.com/105288646/182713176-7e8b0340-0d1a-4d97-8960-5cf5bf8cd79e.png)

**Comment by Ecosanachi** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/105288646/182714269-9b0cee5f-af36-44e4-b8a1-3f7649b7225c.png)
![Screenshot (33)](https://user-images.githubusercontent.com/105288646/182714277-a5b28fcd-c46e-459b-9d4e-f1989f5010e2.png)
![Screenshot (34)](https://user-images.githubusercontent.com/105288646/182714279-323d1d95-9347-4e24-a6f8-a4f5c5d3cf11.png)
![Screenshot (35)](https://user-images.githubusercontent.com/105288646/182714285-5fdce029-bcd6-4c86-a285-f9ced32e968c.png)
![Screenshot (36)](https://user-images.githubusercontent.com/105288646/182714289-293b4196-0364-48c2-b0ff-d83178505156.png)
![Screenshot (37)](https://user-images.githubusercontent.com/105288646/182714291-85407c68-166d-4c7c-b6d0-8a56c9a566b1.png)

**Comment by Holardiplenty123** [comment]
![Landing Page_Desktop](https://user-images.githubusercontent.com/110137932/183244044-2da54bfb-dafc-4a80-8be3-f197b3d9b4da.png)

**Comment by Alatharee21** [comment]
Great.

**Comment by Holardiplenty123** [comment]
![Uploading Landing Page_Desktop.png…]()

**Comment by Holardiplenty123** [comment]
![Uploading Landing Page_Desktop.png…]()

**Comment by Holardiplenty123** [comment]
Done

**Comment by Holardiplenty123** [comment]
![Landing Page_Desktop](https://user-images.githubusercontent.com/110137932/183244844-e01d0967-d3c2-401d-978a-161a48a084e4.png)

**Comment by Horluwatimi** [comment]
![Uploading Desktop (2).png…]()

**Comment by Horluwatimi** [comment]
![Uploading Desktop (2).png…]()

**Comment by Horluwatimi** [comment]
![Uploading Desktop (2).png…]()

**Comment by Horluwatimi** [comment]
<img width="1439" alt="Desktop (2)" src="https://user-images.githubusercontent.com/105248194/183523364-63b8670b-4808-4dc7-8876-bab1d18de08e.png">
