### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by zuriteam78** [zuri-training/tc-gen-team78#3]

**Comment by Ruq23** [comment]
https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/views.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/templates/register.html

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/templates/login.html
