### ISSUE TITLE
Create Hi-fi of Sign in/Sign up page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#30]
Create High-Fidelity of Sign in/Sign up page Design

**Comment by Cokerwhite** [comment]
![Uploading Sign up page.jpg…]()
11:58

**Comment by Cokerwhite** [comment]
![Sign up page (5)](https://user-images.githubusercontent.com/43870085/182727302-88c60fd1-a052-444f-a067-89ed8d9ab53a.jpg)
![Sign in page](https://user-images.githubusercontent.com/43870085/182727363-ebe51f69-c6d9-47fc-8100-7f8ca889ce34.png)
