### ISSUE TITLE
Create Hi-fi of generated text page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#32]
Create High-Fidelity of generated text page Design

**Comment by Samysweet** [comment]
<img width="9280" alt="Generated Text for T C and Privacy Policy" src="https://user-images.githubusercontent.com/105239555/182558337-691dcdfb-f33b-4e55-b60e-2edd51d6348f.png">

**Comment by mogboo** [comment]
Done

**Comment by Efetur** [comment]
Done as well
