### ISSUE TITLE
Create Hi-fi of Team members page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#33]
Create High-Fidelity of team members page design

**Comment by olapizzyCG** [comment]
Done

**Comment by Alatharee21** [comment]
You should export the pages as Png and paste it as comment too if that's possible.

**Comment by Raythelegend** [comment]
![Team Page_Desktop.png](https://user-images.githubusercontent.com/109814671/183242325-9f875d9d-4903-4771-a7bc-0ec2f09dfcd4.png)

**Comment by Raythelegend** [comment]
![Team Page_Tablet.png](https://user-images.githubusercontent.com/109814671/183242362-4e20b4a8-bc4a-43e3-95bf-bb8496a25aa5.png)

**Comment by Raythelegend** [comment]
![Team Page_Mobile.png](https://user-images.githubusercontent.com/109814671/183242377-49650601-225b-437a-a69e-1b7bfa06e895.png)
