### ISSUE TITLE
Create Wireframe, Lo-fi and Hi-fi of contact us page.

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#34]
Create Wireframe, Low-Fidelity and High-Fidelity of contact us page Design.

**Comment by misterdan-a** [comment]
![Contact Us_Hi-Fi_Desktop](https://user-images.githubusercontent.com/105433488/183094099-32eb425a-1318-411d-9de4-4c03b507c8b4.png)
![Contact Us -Dan V2](https://user-images.githubusercontent.com/105433488/183094121-3884e722-d9fa-4c8c-9037-15e2de60c543.png)
![Contact Us -Dan Wireframe](https://user-images.githubusercontent.com/105433488/183094130-8bdfc7d8-97bd-4777-9419-f22fa4f3fc5d.png)

**Comment by misterdan-a** [comment]
Completed.
