### ISSUE TITLE
Create Lo-fi and Hi-fi of Draft page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#36]
Create Low-Fidelity and High-Fidelity of Draft page design

**Comment by misterdan-a** [comment]
![Draft Page_Low-fi](https://user-images.githubusercontent.com/105433488/182852894-246917f9-91a6-4129-aea5-3e75fe383b7d.png)
![Draft Page_Hi-fi_Desktop](https://user-images.githubusercontent.com/105433488/182852921-3e5dc435-d472-4ed1-b533-86120974b76f.png)
![Draft Page_Hi-fi_Mobile](https://user-images.githubusercontent.com/105433488/182852925-8ba0a219-04f2-40e8-b932-b5ddf0219b63.png)
![Draft Page_Hi-fi_Table t](https://user-images.githubusercontent.com/105433488/182852927-100b22f8-7d9f-4534-a47d-cda3f562e83e.png)

**Comment by misterdan-a** [comment]
The files can be found on Figma via
https://www.figma.com/file/FyXNAMzxSQY49B9HW7ElMQ/Proj-t-c-gen-Team78?node-id=1772%3A3438
