### ISSUE TITLE
Make the Landing page Design responsive

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#37]
Design for Tablet and Mobile version

**Comment by Ecosanachi** [comment]
Done
MOBILE
![NQGD6032](https://user-images.githubusercontent.com/105288646/183246160-9bc0f96f-41fd-417f-a2a9-c6d9565922fd.JPG)
TABLET
![tablet](https://user-images.githubusercontent.com/105288646/183246164-f6366713-3844-4733-a6f3-5b79bbf30355.JPG)

**Comment by Ecosanachi** [comment]
Done

**Comment by Alatharee21** [comment]
The image please

**Comment by Holardiplenty123** [comment]
![Uploading Landing Page_Desktop.png…]()

**Comment by Holardiplenty123** [comment]
![Landing Page_Desktop](https://user-images.githubusercontent.com/110137932/183245126-5c537487-47c8-40ec-ba6e-cdc8c44a111b.png)

**Comment by Holardiplenty123** [comment]
![Landing Page_Tablet](https://user-images.githubusercontent.com/110137932/183245163-67abca6d-06d0-4f17-9a91-8a743df293f0.png)

**Comment by Holardiplenty123** [comment]
![Landing Page_Tablet](https://user-images.githubusercontent.com/110137932/183245205-6e3e1b25-3d5a-46ab-9240-e036235bc596.png)

**Comment by Holardiplenty123** [comment]
![Landing Page_Mobile](https://user-images.githubusercontent.com/110137932/183245230-86540a5f-7db8-4559-8fff-fa6e08c180d3.png)

**Comment by Holardiplenty123** [comment]
1) Desktop
2) Tablet
3) Moble 
 Done

**Comment by Horluwatimi** [comment]
![Tablet view](https://user-images.githubusercontent.com/105248194/183523047-e6ed61d9-9eef-4c39-93b4-fc74e959fa12.png)
![Page_Mobile view (1)](https://user-images.githubusercontent.com/105248194/183523083-aa87c22d-12d6-4dcc-94f3-76f2f3bf2148.png)
