### ISSUE TITLE
Make the Sign in/Sign up page Design responsive

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#38]
Design for tablet and mobile

**Comment by Albashirhauwau** [comment]
Done

**Comment by Cokerwhite** [comment]
![Sign In Page_Tablet (1)](https://user-images.githubusercontent.com/43870085/183272393-348e6534-9cd0-43e9-816b-d76c04b2a59b.png)
![Sign up page_Mobile](https://user-images.githubusercontent.com/43870085/183272394-e2855736-81ca-4d0e-a1a0-bae9fc3a2f35.png)
