### ISSUE TITLE
Make the Information entry page Design responsive

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#39]
Design for tablet and mobile

**Comment by misterdan-a** [comment]
![T c2_Tablet](https://user-images.githubusercontent.com/105433488/182855087-21bac8dd-1436-4574-96e0-23eddff96dfe.png)
![PP_Mobile](https://user-images.githubusercontent.com/105433488/182855107-e97853ed-2a13-496c-a4e3-8a6218c4b7fd.png)
![PP_Tablet](https://user-images.githubusercontent.com/105433488/182855116-0f634fff-ec98-4588-9899-cb0f84a59773.png)
![PP2_Mobile](https://user-images.githubusercontent.com/105433488/182855121-e90a0bfe-4b1b-4fc2-b14d-eca874f64e82.png)
![PP2_Tablet](https://user-images.githubusercontent.com/105433488/182855130-40102179-26b7-48ae-81f2-59dcf420eb57.png)
![t c_Mobile](https://user-images.githubusercontent.com/105433488/182855137-aacdcfc7-88cd-4b7d-976a-6a8af2c99f0d.png)
![T C_tablet](https://user-images.githubusercontent.com/105433488/182855143-98ae150f-85b9-4db1-848f-e31eb66106b1.png)
![T c2_Mobile](https://user-images.githubusercontent.com/105433488/182855150-d000424b-1b09-43c1-bd69-5e0e74e5fbff.png)
