### ISSUE TITLE
Make the Text generated page Design responsive

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#40]
Design for tablet and mobile

**Comment by mogboo** [comment]
Done that

**Comment by mogboo** [comment]
![7A28E15E-9EBF-4E03-92EB-2B0AA26D1DC7](https://user-images.githubusercontent.com/71440754/183242980-9d87309e-c968-4fd0-bbec-482e51db9fed.jpeg)
![B9FF05B4-9430-4FC2-A82C-CCA1699FFCFB](https://user-images.githubusercontent.com/71440754/183243005-9574914b-8c5f-4421-b677-28f9ab867541.jpeg)

**Comment by Efetur** [comment]
We all worked on it together. So @mogboo has uploaded it for us
