### ISSUE TITLE
Make the Team members page Design responsive

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#41]
Design for tablet and mobile

**Comment by Raythelegend** [comment]
Done

**Comment by Raythelegend** [comment]
![Uploading z2{f19ca} (ab9b562b-93c7-4024-8de8-7fe283030922 id=0x7f0a03c2 tag=BaseCommentFragment) …]()

**Comment by Raythelegend** [comment]
![Team Page_Tablet.png](https://user-images.githubusercontent.com/109814671/183242930-c8f6f96f-3755-4e72-8bc4-c722084deff5.png)

**Comment by Raythelegend** [comment]
![Team Page_Desktop.png](https://user-images.githubusercontent.com/109814671/183242985-139687b3-dcb3-461b-ae29-a45ce29a9003.png)

**Comment by Raythelegend** [comment]
![Team Page_Mobile.png](https://user-images.githubusercontent.com/109814671/183243035-033f8326-8f74-420e-9e23-36ed34db5236.png)
