### ISSUE TITLE
Make the Contact us page Design responsive

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#42]
Design for tablet and mobile

**Comment by misterdan-a** [comment]
![Contact Us_Hi-Fi_Tablet](https://user-images.githubusercontent.com/105433488/183093768-aa8718e3-1129-4d29-b873-b5cea4bc0917.png)
![Contact Us_Hi-Fi_Desktop](https://user-images.githubusercontent.com/105433488/183093788-cbc13fba-8799-42c3-9b99-74feedea7f10.png)
![Contact Us_Hi-Fi_Mobile](https://user-images.githubusercontent.com/105433488/183093799-91e34604-1e95-4e7a-98dd-7800ef704f41.png)

**Comment by misterdan-a** [comment]
Completed. The header for the tablet view will be updated when a new one is created.
