### ISSUE TITLE
Make the Draft page Design responsive

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#44]
Design for tablet and mobile

**Comment by misterdan-a** [comment]
![Draft Page_Hi-fi_Table t](https://user-images.githubusercontent.com/105433488/182853250-1deb5430-ff9e-4f87-be9a-3c60512e62c3.png)
![Draft Page_Hi-fi_Mobile](https://user-images.githubusercontent.com/105433488/182853284-5de821ee-9658-411a-a1ef-9292d6714049.png)

**Comment by misterdan-a** [comment]
The images in the card will be updated when the templates are ready.
