### ISSUE TITLE
Create FAQ page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#45]
Create responsive FAQ page for the website.

**Comment by Alatharee21** [comment]
@misterdan-a please help me export the FAQ pages and comment them here. Thanks.

**Comment by misterdan-a** [comment]
![FAQ_Open_Mobile](https://user-images.githubusercontent.com/105433488/183313983-987c8333-603f-4478-aa43-a938378f5676.png)
![FAQ_Open_Tablet](https://user-images.githubusercontent.com/105433488/183313986-9dad57be-0762-447f-a99c-7f125ef5313e.png)
![FAQ_Closed_Desktop](https://user-images.githubusercontent.com/105433488/183313987-4ea60586-9545-4d75-a9fa-f69f0ce960be.png)
![FAQ_Closed_Mobile](https://user-images.githubusercontent.com/105433488/183313989-65c12e3f-38eb-4073-aa01-a5680576f808.png)
![FAQ_Closed_Tablet](https://user-images.githubusercontent.com/105433488/183313991-6a7dca9f-9d76-427a-9b08-29c1cb99cb1c.png)
![FAQ_Open_Desktop](https://user-images.githubusercontent.com/105433488/183313993-8f22a87e-1a9f-4c8b-adc8-e581c0a01946.png)

**Comment by misterdan-a** [comment]
The pictures show the look of the pages for both the open and closed states of the accordions.

**Comment by Alatharee21** [comment]
@MarvelousMimi here
