### ISSUE TITLE
Prototype the design pages for presentation.

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#50]
Prototype the design pages for presentation and Usability study Research.

**Comment by misterdan-a** [comment]
[Prototype Links.txt](https://github.com/zuri-training/tc-gen-team78/files/9277512/Prototype.Links.txt)

**Comment by misterdan-a** [comment]
The links to the three flows of the website are in the attached file

**Comment by misterdan-a** [comment]
Desktop Prototype: https://www.figma.com/proto/WyPtWwHOKm6KygXVwTNlFC/Untitled?page-id=0%3A1&node-id=26%3A15489&viewport=1715%2C632%2C0.07&scaling=min-zoom&starting-point-node-id=26%3A15489&show-proto-sidebar=1

Tablet Prototype: https://www.figma.com/proto/WyPtWwHOKm6KygXVwTNlFC/Untitled?page-id=0%3A1&node-id=26%3A10269&viewport=1715%2C632%2C0.07&scaling=min-zoom&starting-point-node-id=26%3A10269&show-proto-sidebar=1

Mobile Prototype: https://www.figma.com/proto/WyPtWwHOKm6KygXVwTNlFC/Untitled?page-id=0%3A1&node-id=26%3A12967&viewport=1715%2C632%2C0.07&scaling=min-zoom&starting-point-node-id=26%3A12967&show-proto-sidebar=1
