### ISSUE TITLE
Usability study Research

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#51]
Carry out usability study Research on the design using prototype of either desktop version, Tablet version or Mobile version.

**Comment by Alatharee21** [comment]
Link to the Usability Research study plan;

https://docs.google.com/document/d/1Lew5XJe4kDPbaq9cHTpwoooy0KFnV1iK/edit?usp=drivesdk&ouid=108136821349163906636&rtpof=true&sd=true

**Comment by Samysweet** [comment]
Done

**Comment by Ecosanachi** [comment]
https://docs.google.com/document/d/1Lew5XJe4kDPbaq9cHTpwoooy0KFnV1iK/edit?usp=sharing&ouid=114436337758927268072&rtpof=true&sd=true

**Comment by Horluwatimi** [comment]
https://docs.google.com/document/d/1Lew5XJe4kDPbaq9cHTpwoooy0KFnV1iK/edit?usp=sharing&ouid=114436337758927268072&rtpof=true&sd=true

**Comment by Holardiplenty123** [comment]
https://docs.google.com/document/d/1Lew5XJe4kDPbaq9cHTpwoooy0KFnV1iK/edit?usp=drivesdk&ouid=108136821349163906636&rtpof=true&sd=true

**Comment by Raythelegend** [comment]
https://docs.google.com/document/d/1Lew5XJe4kDPbaq9cHTpwoooy0KFnV1iK/edit?usp=sharing&ouid=114436337758927268072&rtpof=true&sd=true

**Comment by misterdan-a** [comment]
https://docs.google.com/document/d/1Lew5XJe4kDPbaq9cHTpwoooy0KFnV1iK/edit?usp=sharing&ouid=114436337758927268072&rtpof=true&sd=true

**Comment by Albashirhauwau** [comment]
https://docs.google.com/document/d/1Lew5XJe4kDPbaq9cHTpwoooy0KFnV1iK/edit?usp=drivesdk&ouid=108136821349163906636&rtpof=true&sd=true
