### ISSUE TITLE
Create User profile page

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#55]

**Comment by misterdan-a** [comment]
![User Profile_Hovering on Image_Desktop](https://user-images.githubusercontent.com/105433488/183597631-a9cd1ee5-254f-4eb2-95c1-54a415777969.png)
![User Profile_Default_Desktop](https://user-images.githubusercontent.com/105433488/183597639-2a5a2e0a-fea4-4530-a6eb-3c76ba4ab4b8.png)
![User Profile_Default_Mobile](https://user-images.githubusercontent.com/105433488/183597642-6c77056e-0a96-476d-b5b0-b596b6f01b58.png)
![User Profile_Default_Tablet](https://user-images.githubusercontent.com/105433488/183597643-217866a5-c8d1-4e56-a369-f8b3165f4265.png)

**Comment by misterdan-a** [comment]
The desktop view has two modes to indicate that the user has the option to edit profile picture when the user hovers on the profile picture displayed.
