### ISSUE TITLE
Create alert overlays

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#57]

**Comment by misterdan-a** [comment]
These are alert overlays for different issues during the user journey.
![Save   Continue Overlay_Desktop](https://user-images.githubusercontent.com/105433488/183598876-b033e3a4-79c5-49c4-880e-4b1a7456975f.png)
![Delete account_Desktop](https://user-images.githubusercontent.com/105433488/183598880-521ee85d-5f8f-46da-877e-a32f1cc61736.png)
![Password Reset_Desktop](https://user-images.githubusercontent.com/105433488/183598883-8f55c03c-4507-42b2-9847-55d3702d247f.png)
![Password Updated_Desktop](https://user-images.githubusercontent.com/105433488/183598886-0894b3b1-7d4b-44b3-925a-d1a64b153fcc.png)
![Progress Saved Overlay_Desktop](https://user-images.githubusercontent.com/105433488/183598890-98c98916-ce98-4f22-a75d-75cb4661e9a3.png)
