### ISSUE TITLE
slug identifier

### ISSUE THREAD

**Issue by zuriteam78** [zuri-training/tc-gen-team78#58]

**Comment by Ruq23** [comment]
https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/tcdem/utils.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/views.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/models.py
