### ISSUE TITLE
Authentication (front End)

### ISSUE THREAD

**Issue by zuriteam78** [zuri-training/tc-gen-team78#6]
Work with the designers for the Login and Registration pages

**Comment by Blesyn1** [comment]
https://github.com/zuri-training/tc-gen-team78/blob/test/projdoc/frontEnd/home/auth/login.html

**Comment by Blesyn1** [comment]
https://github.com/zuri-training/tc-gen-team78/blob/test/projdoc/frontEnd/home/auth/login.css

**Comment by Blesyn1** [comment]
https://github.com/zuri-training/tc-gen-team78/blob/test/projdoc/frontEnd/home/auth/signup.html

**Comment by Blesyn1** [comment]
https://github.com/zuri-training/tc-gen-team78/tree/test/projdoc/frontEnd/home/auth

**Comment by Blesyn1** [comment]
I created the Login page and Sign up page (Authentication) and made it responsive. 

I clone the repository and started my task without "Forking" before cloning, I think that is why i was not able to link my pull request to my issue #6.

**Comment by Blesyn1** [comment]
https://github.com/zuri-training/tc-gen-team78/tree/test/projdoc/frontEnd/home/auth

I created the Login page and Sign up page (Authentication) and made it responsive.

I clone the repository and started my task without "Forking" before cloning, I think that is why i was not able to link my pull request to my issue https://github.com/zuri-training/tc-gen-team78/issues/6.

**Comment by Blesyn1** [comment]
https://github.com/zuri-training/tc-gen-team78/tree/test/projdoc/frontEnd/home/auth

I created the Login page and Sign up page (Authentication) and made it responsive.

I cloned the repository and started my task without "Forking" before cloning, I think that is why I have not able to link my pull request to my issue https://github.com/zuri-training/tc-gen-team78/issues/6.

**Comment by Blesyn1** [comment]
https://github.com/zuri-training/tc-gen-team78/tree/test/projdoc/frontEnd/home/auth

I created the Login page and Sign up page (Authentication) and made it responsive.

I cloned the repository and started my task without "Forking" before cloning, I think that is why I have not been able to link my pull request to the issue assigned to me issue https://github.com/zuri-training/tc-gen-team78/issues/6.
