### ISSUE TITLE
templating for frontend

### ISSUE THREAD

**Issue by zuriteam78** [zuri-training/tc-gen-team78#61]
get the html pages from the front end folder and add it to the django backend using jinja format

**Comment by Ruq23** [comment]
https://github.com/zuri-training/tc-gen-team78/tree/last-branch/tcfinal/templates

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/views.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/urls.py
