### ISSUE TITLE
details collection and saving to the backend

### ISSUE THREAD

**Issue by zuriteam78** [zuri-training/tc-gen-team78#62]

**Comment by Ruq23** [comment]
https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/views.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/models.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/urls.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/templates/tcform.html
