### ISSUE TITLE
faq frontend

### ISSUE THREAD

**Issue by zuriteam78** [zuri-training/tc-gen-team78#64]

**Comment by Lftobs** [comment]
Links to commits for issues:
FAQs
https://github.com/zuri-training/tc-gen-team78/commit/250cedf27c72da832ce055fff13a63fe1817aaa6

Other issues worked on :
Draft page
https://github.com/zuri-training/tc-gen-team78/commit/d7da1792cd4f047fef214c5ade46b0ab208744fc

Generated page
https://github.com/zuri-training/tc-gen-team78/commit/bdd8c6c9779115a8b5ebdf4ffebe365dbf3c9f9d

Issue 76
https://github.com/zuri-training/tc-gen-team78/issues/76

profile page
https://github.com/zuri-training/tc-gen-team78/commit/098e437eb1d98d08c122ba8b53f11608f26793aa
