### ISSUE TITLE
create a user draft page backend structure

### ISSUE THREAD

**Issue by zuriteam78** [zuri-training/tc-gen-team78#69]

**Comment by Ruq23** [comment]
https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/views.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/models.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/account/urls.py

https://github.com/zuri-training/tc-gen-team78/blob/last-branch/tcfinal/templates/draft.html
