### ISSUE TITLE
Draft Presentation slides and Documentation.

### ISSUE THREAD

**Issue by Alatharee21** [zuri-training/tc-gen-team78#82]
This should include the analysis of the Usability Study Research; Note-taking, Affinity diagram and Themes & Actionable insights that was derived from the analysis.

**Comment by Efetur** [comment]
![IMG-20220808-WA0003](https://user-images.githubusercontent.com/105781279/184552961-e8e1eea1-a16c-4084-bfd5-2afd1024dcd3.jpeg)
![IMG-20220808-WA0006](https://user-images.githubusercontent.com/105781279/184552964-2e9af694-d539-4b10-9559-f26de535986e.jpeg)
![IMG-20220808-WA0008](https://user-images.githubusercontent.com/105781279/184552965-1d0e2f5e-8983-444c-b14d-aba3909fecba.jpeg)
![IMG-20220808-WA0011](https://user-images.githubusercontent.com/105781279/184552966-85a50358-99c3-4197-b8bf-f292e0511f80.jpeg)
![IMG-20220808-WA0014](https://user-images.githubusercontent.com/105781279/184552969-1f8ee79d-32da-4193-acf5-4427b567b56f.jpeg)
![IMG-20220808-WA0016](https://user-images.githubusercontent.com/105781279/184552971-6bc6778c-70d1-45d2-a13f-9a70b53834fd.jpeg)
![20220814_205529](https://user-images.githubusercontent.com/105781279/184552974-8edef7dc-4c8b-4bfc-bbc8-9baf59af3906.jpg)
![Affinity diagram](https://user-images.githubusercontent.com/105781279/184552975-c30df88f-c986-4bc1-94d7-b1a96e74d354.png)

**Comment by Efetur** [comment]
Note taking and Affinity Diagram above

**Comment by Efetur** [comment]
Affinity Diagram: https://www.figma.com/file/UENW5ZoWasDjwAgrmn8gec/Affinity-Diagram?node-id=0%3A1
Themes and Actionable Insights: https://docs.google.com/document/d/1XIrCoaSo0thlbRQx5l4z7Ps4iZ6EixmSgIxJAxGT_zA/edit?usp=sharing

**Comment by Efetur** [comment]
Presentation slide: https://docs.google.com/presentation/d/1swQEV4S0K1NXGKzatSaIneqEjHL7_qP7pbYFFp7ZRP0/edit?usp=sharing

**Comment by Ecosanachi** [comment]
Link to the documentation.

https://docs.google.com/document/d/1gxPTYpCzXAn_DR2CloNJpd3_TPzWTT5gjadmTzHjuRs/edit
